
server:
  port: 3012
eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://test:123456@localhost:3000/eureka/
  instance:
    preferIpAddress: true
spring:
  application:
    name: config-eureka-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MalcolmFF/springboot-config-temp #配置文件所在仓库
          username: MalcolmFF #登录账号
          password: MalcolmFeng1234 #登录密码
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
